@startuml employee

package HumanResourcesModule {

	class Employee {
		+ employeeId: int
		+ name: String
		+ email: String
		+ position: enum
		+ department: enum

		+ changeName() 
		+ changeEmail() 
		+ changePosition() 
		+ changeDepartment() 
	}

	class EmployeeAdmissionForm {
		+ formId: int
		+ dateSubmitted: Date
		+ applicant: Employee
		
		+ alterDate()
		+ alterApplicant()
	}

	class PayrollManager {
		+ managerId: int
		+ managerName: String

		+ updateManagerName()
		+ generatePayroll(employee: Employee): PayrollForm
	}

	class PayrollForm {
		+ formId: int
		+ employee: Employee
		+ payPeriod: Date
		+ netSalary: double
		
		+ updateEmployee()
		+ updatePayPeriod()
		+ updateNetSalary()

	}

	class LMS {
		+ lmsId: int
		+ name: String
		
		+ updateName()
	}

	class PayslipApprovalSystem {
		+ systemId: int

		+ approvePayslip(payslip: PayrollForm)
		+ rejectPayslip(payslip: PayrollForm)
	}

	class SearchSystem {
		+ searchId: int
		+ searchQuery: string
		
		+ search(keyword: String): List<Object>
	}

	class Admin {
		- adminId: int
		- adminName: String
		+ getInstance(): Admin
		+ getAdminId(): int
		+ getAdminName(): String
	}

	Employee "1" --o "1" EmployeeAdmissionForm : fills out
	PayrollManager "1" --o "*" PayrollForm : generates
	Employee "1" --o "*" PayrollForm : has
	LMS "1" --o "0..*" Employee : uses
	PayslipApprovalSystem "1" -- "1" Admin : uses
	Admin "1" -- "1" Employee : is an instance of

	SearchSystem "1" -- "0..*" "Employee": searches
}
@enduml
