@startuml employee

package HumanResourcesModule {

	class Employee {
		+ employeeId: int
		+ name: String
		+ email: String
		+ position: enum
		+ department: enum
		+ isAdmin: bool
		+ onLeave: bool

		+ changeName() 
		+ changeEmail() 
		+ changePosition() 
		+ changeDepartment()
		+ updateLeaveStatus(bool): int 
	}

	class EmployeeAdmissionForm {
		+ formId: int
		+ dateSubmitted: Date
		+ applicant: Employee
		
		+ alterDate()
		+ alterApplicant()
	}

	class PayrollManager {
		+ payrollForms: List<PayrollForm>

		+ generatePayroll(employee: Employee): PayrollForm
		+ addPayrollForm(payrollForm: PayrollForm): int
		+ removePayrollForm(formId: int): int
		+ viewAllPayrollForms(): int
		+ viewPayrollForm(formID | employeeID): int
	}

	class PayrollForm {
		+ formId: int
		+ employee: Employee
		+ payPeriod: Date
		+ netSalary: double
		
		+ updateEmployee()
		+ updatePayPeriod()
		+ updateNetSalary()

	}

	class LMS {
		+ LeavesAvailable: Map<date, bool>
		
		+ updateName()
		+ addLeave()
		+ remitLeave()
		'Only visible to the admin
		+ approveLeave(password) 
	}

	class PayslipApprovalSystem {
		+ systemId: int

		+ approvePayslip(payslip: PayrollForm)
		+ rejectPayslip(payslip: PayrollForm)
	}

	class SearchSystem {
		+ searchId: int
		+ searchQuery: string
		
		+ search(keyword: String): List<Object>
		+ searchEmployee(employeeID: int): int
		+ searchPayrollForm(formID: int): int
	}

	class Admin extends Employee{
		- adminId: int
		- adminName: String
		+ getInstance(): Admin
		+ getAdminId(): int
		+ getAdminName(): String
	}

	class EmployeeDatabase {
		+ employees: List<Employee>
		+ num_employees: int
		+ num_admins: int

		+ addEmployee(employeeId: int): int
		+ removeEmployee(employeeId: int): int
		- updateEmployeeNumber(): int
		+ setEmployeeAsAdmin(employeeID: int, password: string): int
		+ removeEmployeeAsAdmin(employeeID: int, password: string): int
		- updateAdminNumber(): int
	}

	Admin "1..*" -- "1" PayslipApprovalSystem: approves payslip using
	Employee "1.." --> "1" LMS: applies leaves on
	Employee "1..*" --> "1" PayrollForm: fills
	Admin "1.." --> "1" SearchSystem: searches on
	SearchSystem "1" --> "1" EmployeeDatabase: uses
	' Employees can fill the employee admission form, while their position can be an applicant
	Employee "1..*" --> "1" EmployeeAdmissionForm: fills
	Admin "1..*" --> "1..*" EmployeeAdmissionForm: can fill on behalf of employee
	PayrollManager "1" --> "1" EmployeeDatabase: uses
	PayrollForm "1" --> PayrollManager: interfaces with / stores
	SearchSystem "1" --> PayrollManager: uses
	PayslipApprovalSystem "1" --> "1" PayrollManager: interfaces with
	Admin "1" --> "1" LMS: approves leaves using
}
@enduml
