@startuml
package ManageUsersModule {
    class AdminUser {
        - userID: int
        - name: string
    }
    class User {
        - userID: int
        - name: string
    }

    class SearchSystem {
        + searchQuery: string
        + searchResults: List<User>

        + addSearchQuery(query: string): void
        + updateSearchQuery(query: string): void
        + viewProfileBasedOnRoles(roles: List<role>): void
        + search(): void
    }

    class UserManager {
        + roles: List<enum>
        + privileges: List<enum>
        
        + viewAllRoles(): void
        + viewAllPrivileges(): void
        + addNewRole(role: enum): void
        + removeRole(role: enum): void
        + updatePassword(user: User): void
        + addNewPrivilege(privilege: enum): void
        + removePrivileges(privilege: enum): void
        + editUser(userID: int): void
        + updateRole(userID: int, role: enum): void
        + updatePrivileges(userID: int, privilege: enum): void
        + setStandards(): void
    }

    User "1" -- "0..*" SearchSystem : "Uses for searching"
    AdminUser "1" -- "0..*" SearchSystem : "Uses for searching"
    AdminUser "1..*" -- "0..*" UserManager : "Manages"
}
@enduml
