@startuml manageNews
package NewsModule {
    class News {
        - id: int
        - title: string
        - content: string
        - date: string
        - comments: List<Comment>
        + readNews(id: int): void
        + updateNews(id: int, title: string, content: string, date: string): void
        + updateNews(id: int, content: string, date: string): void
        + deleteNews(title: string): void
        + createNews(title: string, content: string, date: string): void
    }

    class Comment {
        - id: int
        - content: string
        - date: string
        - author: string
        - status: string
        + addComment(content: string, author: string, date: string, id: int): void
        + deleteComment(id: int): void
    }

    News "1" o-- "0..*" Comment : "Has Comments"

    class ArchivedNews {
        - archiveId: int
        - newsId: int
        + archiveNews(newsId: int): void
        + unarchiveNews(newsId: int): void
    }

    News <|-- ArchivedNews : "Archived News"
}
@enduml
