@startuml messages

class User {

}

class Message {
    + messageID: int
    + sender_ID: int
    + recipient_IDs: list<int>
    + message Content: string
    + timestamp: date
}

class CommunicationRecordingSystem {
    + messageIDs: List<int>

	+ getAllRecordings()
	+ deleteAllRecordings(password)
	+ getRecording(messageID)
	+ deleteRecording(messageID)
}

class Broadcaster {
    + Message_ID: string
	+ Sender_ID: int
	+ receipient_group_ids: list<int>

}
@enduml